// Generates src/icons.tsx from svgs/*.svg.
// Each SVG becomes an exported React component using <IconBase>.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SVG_DIR = join(ROOT, 'svgs');
const OUT = join(ROOT, 'src', 'icons.tsx');
const OUT_METADATA = join(ROOT, 'src', 'metadata.ts');

const THEME_COLOR_HEX = ['161924', '1C1B1F', '323232', '231F20'];
const THEME_COLOR = new RegExp(`#(?:${THEME_COLOR_HEX.join('|')})`, 'gi');

const KEBAB_ATTRS = {
  'clip-path': 'clipPath',
  'clip-rule': 'clipRule',
  'fill-rule': 'fillRule',
  'stroke-dasharray': 'strokeDasharray',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-width': 'strokeWidth',
  'stroke-miterlimit': 'strokeMiterlimit',
};

function camelizeAttrs(s) {
  for (const [k, v] of Object.entries(KEBAB_ATTRS)) {
    s = s.replace(new RegExp(`\\b${k}=`, 'g'), `${v}=`);
  }
  return s;
}

function convertStyleAttrs(s) {
  // style="a:b;c:d" -> style={{ a: "b", c: "d" }} with camelCased keys
  return s.replace(/style="([^"]*)"/g, (_, body) => {
    const pairs = body
      .split(';')
      .map((p) => p.trim())
      .filter(Boolean)
      .map((p) => {
        const idx = p.indexOf(':');
        if (idx === -1) return null;
        const key = p.slice(0, idx).trim();
        const value = p.slice(idx + 1).trim();
        const camel = key.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
        return `${JSON.stringify(camel)}: ${JSON.stringify(value)}`;
      })
      .filter(Boolean);
    return `style={{${pairs.join(', ')}}}`;
  });
}

function stripOuterSvg(svg) {
  const openMatch = svg.match(/<svg[^>]*>/i);
  const closeIdx = svg.lastIndexOf('</svg>');
  if (!openMatch || closeIdx === -1) return null;
  const outerTag = openMatch[0];
  return {
    inner: svg.slice(openMatch.index + outerTag.length, closeIdx).trim(),
    outer: outerTag,
  };
}

function detectVariant(rawInner) {
  // Look at the *inner* content before color normalization. If any element fills with
  // the brand colors or hardcoded dark ink swatches used as fill,
  // treat the icon as fill-variant. Defs/clipPath fills use "white" or "#D9D9D9" so they
  // don't trigger this.
  return new RegExp(`fill=\"#(?:${THEME_COLOR_HEX.join('|')})\"`, 'i').test(
    rawInner,
  )
    ? 'fill'
    : 'stroke';
}

function transformInner(inner) {
  // 1) detect variant from the raw inner content (before color rewrites)
  const variant = detectVariant(inner);

  // 2) normalize fixed colors -> currentColor
  let out = inner.replace(THEME_COLOR, 'currentColor');

  // 3) remove attributes that will cascade from <svg>:
  //    stroke, fill (when currentColor), and shared stroke modifiers
  out = out
    .replace(/\s+stroke="currentColor"/g, '')
    .replace(/\s+stroke-width="1\.5"/g, '')
    .replace(/\s+stroke-linecap="round"/g, '')
    .replace(/\s+stroke-linejoin="round"/g, '');

  if (variant === 'fill') {
    out = out.replace(/\s+fill="currentColor"/g, '');
  }

  // 4) drop stray xmlns on inner elements (rare, but cheap)
  out = out.replace(/\s+xmlns="[^"]*"/g, '');

  // 5) kebab → camel for the rest, and convert string style="" to JSX object form
  out = camelizeAttrs(out);
  out = convertStyleAttrs(out);

  // 6) collapse whitespace between tags
  out = out.replace(/>\s+</g, '><').trim();

  return { inner: out, variant };
}

function toPascalCase(name) {
  let s = name
    .replace(/\.svg$/i, '')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim();
  if (!s) s = 'Unnamed';
  s = s
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
  // Always prefix to ensure valid identifier (digit start) and consistent namespace.
  return `Icon${s}`;
}

function main() {
  const files = readdirSync(SVG_DIR)
    .filter((f) => f.toLowerCase().endsWith('.svg'))
    .sort();
  console.log(`Found ${files.length} svg files`);

  const usedNames = new Set();
  const entries = [];
  let skipped = 0;

  for (const file of files) {
    const raw = readFileSync(join(SVG_DIR, file), 'utf8');
    const parsed = stripOuterSvg(raw);
    if (!parsed) {
      console.warn(`skip (no <svg>): ${file}`);
      skipped++;
      continue;
    }
    const { inner: body, variant } = transformInner(parsed.inner);

    const base = toPascalCase(basename(file));
    let name = base;
    let n = 2;
    while (usedNames.has(name)) {
      name = `${base}_${n++}`;
    }
    usedNames.add(name);

    entries.push({ name, variant, body, source: file });
  }

  const header = `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
/* eslint-disable */
import { IconBase, type IconProps } from "./IconBase";
import type { ForwardRefExoticComponent, RefAttributes } from "react";
import { forwardRef } from "react";

export type Icon = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>;

`;

  const body = entries
    .map(
      ({ name, variant, body }) =>
        `export const ${name}: Icon = /*#__PURE__*/ forwardRef((props, ref) => (
  <IconBase ref={ref}${variant === 'fill' ? ' variant="fill"' : ''} {...props}>${body}</IconBase>
));
${name}.displayName = ${JSON.stringify(name)};`,
    )
    .join('\n\n');

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, header + body + '\n');
  writeFileSync(
    OUT_METADATA,
    `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.\n/* eslint-disable */\nexport const iconCount = ${entries.length};\n`,
  );
  console.log(`Wrote ${entries.length} icons to ${OUT} (skipped ${skipped})`);
}

main();
